# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "tdcall"
edition.workspace = true
rust-version.workspace = true

[features]
default = []
tracing = ["dep:tracing_no_std", "dep:log"]

[dependencies]
hvdef.workspace = true
memory_range.workspace = true
thiserror.workspace = true
x86defs.workspace = true
log = { workspace = true, optional = true }

tracing_no_std = { workspace = true, optional = true }

[lints]
workspace = true
